"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Activity, Bot, Boxes, Braces, ChevronRight, CircleStop, CloudCog, Code2, Database, FileCode2, Gauge, GitBranch, Globe2, LayoutDashboard, ListRestart, LogOut, MoreHorizontal, Network, Play, Plus, Rocket, Search, Server, Settings, ShieldCheck, SquareTerminal, X, Zap } from "lucide-react";
import { branding } from "@/config/branding";

type Project = { id: string; name: string; slug: string; type: string; runtime: string; status: string; sourceType: string; branch: string | null; updatedAt: string; internalPort: number | null; memoryMb: number; cpuLimit: number; deployments: { id: string; status: string; createdAt: string }[]; _count: { variables: number } };
type Draft = { name: string; type: "DISCORD_BOT" | "TELEGRAM_BOT" | "WHATSAPP_INTEGRATION" | "WEB_SERVICE" | "BACKGROUND_WORKER" | "STATIC_WEBSITE" | "API" | "SCHEDULED_JOB"; sourceType: "GITHUB" | "GIT" | "ZIP" | "EMPTY" | "TEMPLATE"; runtimeKey: "node" | "python" | "java" | "go" | "rust" | "php" | "docker" | "static"; repositoryUrl: string; branch: string; startCommand: string; installCommand: string; buildCommand: string; internalPort: string; memoryMb: string; cpuLimit: string };
const blankDraft: Draft = { name: "", type: "WEB_SERVICE", sourceType: "EMPTY", runtimeKey: "node", repositoryUrl: "", branch: "main", startCommand: "npm start", installCommand: "npm ci", buildCommand: "npm run build", internalPort: "3000", memoryMb: "512", cpuLimit: "0.5" };
const nav = [{ label: "Overview", icon: LayoutDashboard }, { label: "Projects", icon: Boxes }, { label: "Deployments", icon: Rocket }, { label: "Monitoring", icon: Activity }, { label: "Nodes", icon: Server }, { label: "Templates", icon: FileCode2 }, { label: "Audit logs", icon: ShieldCheck }, { label: "Settings", icon: Settings }];
const sourceOptions = [{ value: "GITHUB", icon: GitBranch, label: "GitHub repository", text: "Connect with OAuth when configured" }, { value: "GIT", icon: Code2, label: "Git URL", text: "Clone an authorized repository" }, { value: "ZIP", icon: Database, label: "Upload ZIP", text: "Runner accepts validated archives" }, { value: "EMPTY", icon: Braces, label: "Empty project", text: "Start with a managed workspace" }, { value: "TEMPLATE", icon: FileCode2, label: "Project template", text: "Use a reviewed starter" }];
const runtimeDefaults: Record<Draft["runtimeKey"], Pick<Draft, "installCommand" | "buildCommand" | "startCommand" | "internalPort">> = { node: { installCommand: "npm ci", buildCommand: "npm run build", startCommand: "npm start", internalPort: "3000" }, python: { installCommand: "pip install -r requirements.txt", buildCommand: "", startCommand: "python main.py", internalPort: "" }, java: { installCommand: "./mvnw dependency:resolve", buildCommand: "./mvnw package", startCommand: "java -jar target/*.jar", internalPort: "8080" }, go: { installCommand: "", buildCommand: "go build -o app .", startCommand: "./app", internalPort: "8080" }, rust: { installCommand: "", buildCommand: "cargo build --release", startCommand: "./target/release/app", internalPort: "" }, php: { installCommand: "composer install --no-dev", buildCommand: "", startCommand: "php -S 0.0.0.0:8080 -t public", internalPort: "8080" }, docker: { installCommand: "", buildCommand: "", startCommand: "Dockerfile CMD", internalPort: "" }, static: { installCommand: "npm ci", buildCommand: "npm run build", startCommand: "npx serve -s dist -l 3000", internalPort: "3000" } };

function statusName(status: string) { return status.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase()); }
function relative(date: string) { const seconds = Math.max(0, Math.round((Date.now() - new Date(date).getTime()) / 1000)); return seconds < 60 ? "just now" : seconds < 3600 ? `${Math.floor(seconds / 60)}m ago` : `${Math.floor(seconds / 3600)}h ago`; }
function statusClass(status: string) { const value = status.toLowerCase(); return value === "running" ? "running" : value === "failed" || value.includes("failed") ? "failed" : value === "queued" ? "queued" : value === "draft" || value === "stopped" ? value : "deploying"; }

export function DashboardClient({ initialProjects, user }: { initialProjects: Project[]; user: { username: string; role: string } }) {
  const [projects, setProjects] = useState(initialProjects); const [view, setView] = useState("Overview"); const [showWizard, setShowWizard] = useState(false); const [notice, setNotice] = useState(""); const [search, setSearch] = useState(""); const [logProject, setLogProject] = useState<Project | null>(null);
  const filtered = useMemo(() => projects.filter((project) => project.name.toLowerCase().includes(search.toLowerCase()) || project.runtime.toLowerCase().includes(search.toLowerCase())), [projects, search]);
  const running = projects.filter((project) => project.status === "RUNNING").length; const failed = projects.filter((project) => project.status === "FAILED").length;
  async function refresh() { const response = await fetch("/api/projects", { cache: "no-store" }); if (response.ok) setProjects((await response.json()).projects); }
  async function projectAction(project: Project, action: "start" | "stop" | "restart" | "rebuild") { setNotice(`${statusName(action)} requested for ${project.name}…`); const response = await fetch(`/api/projects/${project.id}/actions`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action }) }); const data = await response.json(); setNotice(response.ok ? `${statusName(action)} request sent to isolated runner.` : data.error || "Action could not be completed."); if (response.ok) await refresh(); }
  async function signOut() { await fetch("/api/auth/logout", { method: "POST" }); window.location.assign("/login"); }
  const title = view === "Overview" ? "Command center" : view;
  return <main className="ambient shell" style={{ "--background-image": `url(${branding.dashboardBackgroundUrl})` } as React.CSSProperties}>
    <aside className="glass sidebar"><div className="brand"><img className="brand-logo" src={branding.logoUrl} onError={(event) => { event.currentTarget.src = branding.fallbackLogo; }} alt="SULAYER CLOUD logo" /><div className="brand-text"><span>{branding.productName}</span><small>CONTROL PLANE</small></div></div><nav className="nav" aria-label="Primary navigation">{nav.map(({ label, icon: Icon }) => <button key={label} className={view === label ? "active" : ""} onClick={() => setView(label)}><Icon size={17} /><span>{label}</span></button>)}</nav><div className="sidebar-spacer" /><div className="safe-mode"><b>● Authorized workloads only</b>Containers run isolated and unprivileged by default.</div><button className="soft-button" onClick={signOut} aria-label="Sign out"><LogOut size={16} style={{ verticalAlign: "middle", marginRight: 8 }} /><span className="brand-text">Sign out</span></button></aside>
    <section className="main"><header className="glass topbar"><div><h1>{title}</h1><div className="tiny">Self-hosted operations · <span style={{ color: "var(--success)" }}>● Runner policy enabled</span></div></div><label className="search"><span className="sr-only">Search projects</span><Search size={14} style={{ position: "absolute", margin: "13px", color: "var(--text-muted)" }} /><input className="field" style={{ paddingLeft: 35, minHeight: 39 }} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search projects" /></label><button className="neon-button" onClick={() => setShowWizard(true)}><Plus size={16} style={{ verticalAlign: "middle", marginRight: 7 }} />Add project</button><div title={`${user.username} (${user.role})`} className="avatar">{user.username.slice(0, 2).toUpperCase()}</div></header>
      <div className="dashboard"><div className="page-header"><div><p className="eyebrow">{view === "Overview" ? "SYSTEM OVERVIEW" : "OPERATIONS"}</p><h2>{view === "Overview" ? "Good to see you online." : `${title} workspace`}</h2><p className="muted" style={{ margin: "7px 0 0", fontSize: 13 }}>{view === "Overview" ? "Your authorized applications at a glance." : "Use the controls below to manage your authorized infrastructure."}</p></div><button className="soft-button" onClick={refresh}><ListRestart size={15} style={{ verticalAlign: "middle", marginRight: 7 }} />Refresh data</button></div>
        {notice && <div className="glass section" role="status" style={{ padding: "11px 14px", color: "var(--text-secondary)", fontSize: 13 }}>{notice}<button className="icon-button" style={{ float: "right", marginTop: -5 }} onClick={() => setNotice("")} aria-label="Dismiss notification"><X size={15} /></button></div>}
        <div className="metrics"><Metric label="Total projects" value={String(projects.length)} foot={`${running} currently running`} icon={<Boxes size={16} />} /><Metric label="CPU allocation" value={`${projects.reduce((sum, p) => sum + p.cpuLimit, 0).toFixed(1)} cores`} foot="Limits set by control plane" icon={<Gauge size={16} />} /><Metric label="Memory allocation" value={`${projects.reduce((sum, p) => sum + p.memoryMb, 0)} MB`} foot="Configured container maximums" icon={<Database size={16} />} /><Metric label="Deployment health" value={failed ? `${failed} failed` : "Healthy"} foot={failed ? "Review failed deployment logs" : "No failed deployments"} icon={<Activity size={16} />} danger={Boolean(failed)} /></div>
        <div className="split"><section className="glass section"><div className="section-title"><div><h3>{view === "Deployments" ? "Recent deployments" : "Project status"}</h3><span className="tiny">{filtered.length ? `${filtered.length} managed project${filtered.length === 1 ? "" : "s"}` : "No matching projects"}</span></div><button className="icon-button" aria-label="Add a project" onClick={() => setShowWizard(true)}><Plus size={18} /></button></div>{filtered.length ? <div className="project-list">{filtered.map((project) => <article className="project-row" key={project.id}><div className="project-icon">{project.type.includes("BOT") ? <Bot size={19} /> : project.type === "API" ? <Network size={19} /> : <Globe2 size={19} />}</div><div className="project-main"><b>{project.name}</b><span className="mono">{project.runtime} · {project.internalPort ? `:${project.internalPort}` : "worker"} · {project._count.variables} vars</span></div><span className={`status ${statusClass(project.status)}`}>{statusName(project.status)}</span><div className="actions"><button className="icon-button" aria-label={`Open ${project.name} logs`} title="Logs" onClick={() => setLogProject(project)}><SquareTerminal size={15} /></button><button className="icon-button" aria-label={`Start ${project.name}`} title="Start" onClick={() => projectAction(project, "start")}><Play size={15} /></button><button className="icon-button" aria-label={`Restart ${project.name}`} title="Restart" onClick={() => projectAction(project, "restart")}><ListRestart size={15} /></button><button className="icon-button" aria-label={`Stop ${project.name}`} title="Stop" onClick={() => projectAction(project, "stop")}><CircleStop size={15} /></button><button className="icon-button" aria-label={`Rebuild ${project.name}`} title="Rebuild" onClick={() => projectAction(project, "rebuild")}><Rocket size={15} /></button></div></article>)}</div> : <Empty onCreate={() => setShowWizard(true)} />}</section>
          <aside className="glass section"><div className="section-title"><div><h3>Recent activity</h3><span className="tiny">Audit-aware control events</span></div><ShieldCheck size={18} color="var(--accent-cyan)" /></div><div className="activity">{projects.slice(0, 4).map((project) => <div className="activity-row" key={project.id}><i className="activity-dot" /><div><b>{project.name} · {statusName(project.status)}</b><span>{project.deployments[0] ? `Latest deployment ${statusName(project.deployments[0].status)}` : "Project configuration saved"}</span></div><time>{relative(project.updatedAt)}</time></div>)}{!projects.length && <p className="tiny">Events will appear after you create your first project.</p>}</div></aside></div>
        <section className="glass section"><div className="section-title"><div><h3>Resource telemetry</h3><span className="tiny">Runner-fed samples appear here after an application is deployed.</span></div><span className="status stopped">Awaiting telemetry</span></div><div className="chart" aria-label="CPU and memory chart awaiting runner telemetry"><svg viewBox="0 0 700 175" preserveAspectRatio="none" aria-hidden="true"><path d="M0 143 C70 122,85 135,140 105 S230 130,285 88 S370 115,430 72 S520 100,570 54 S645 79,700 29" fill="none" stroke="#2ddcff" strokeWidth="2" opacity=".65" /><path d="M0 158 C72 154,110 135,170 142 S270 99,330 119 S440 85,490 104 S590 69,700 91" fill="none" stroke="#8d5cff" strokeWidth="2" opacity=".6" /></svg></div><div className="chart-labels"><span>15 min</span><span>10 min</span><span>5 min</span><span>Now</span></div></section>
      </div></section><nav className="glass mobile-nav" aria-label="Mobile navigation">{nav.slice(0, 5).map(({ label, icon: Icon }) => <button aria-label={label} title={label} className={view === label ? "active" : ""} onClick={() => setView(label)} key={label}><Icon size={18} /></button>)}</nav>{showWizard && <ProjectWizard onClose={() => setShowWizard(false)} onCreated={async (message) => { setShowWizard(false); setNotice(message); await refresh(); }} />}{logProject && <LogModal project={logProject} onClose={() => setLogProject(null)} />}</main>;
}

function Metric({ label, value, foot, icon, danger }: { label: string; value: string; foot: string; icon: React.ReactNode; danger?: boolean }) { return <article className="glass metric"><div className="metric-top"><span>{label}</span><span style={{ color: danger ? "var(--danger)" : "var(--accent-cyan)" }}>{icon}</span></div><div className="metric-value" style={danger ? { color: "var(--danger)" } : undefined}>{value}</div><div className="metric-foot">{foot}</div><div className="metric-line" style={danger ? { background: "linear-gradient(90deg,var(--danger),transparent)" } : undefined} /></article>; }
function Empty({ onCreate }: { onCreate: () => void }) { return <div style={{ textAlign: "center", padding: "38px 15px" }}><CloudCog size={29} color="var(--accent-cyan)" /><h4 style={{ margin: "12px 0 5px" }}>Your control center is ready.</h4><p className="tiny" style={{ margin: "0 0 17px" }}>Deploy an authorized app to begin collecting logs and metrics.</p><button className="neon-button" onClick={onCreate}>Deploy your first project</button></div>; }

function LogModal({ project, onClose }: { project: Project; onClose: () => void }) {
  const [logs, setLogs] = useState("Loading deployment output…\n"); const [status, setStatus] = useState("");
  useEffect(() => { const events = new EventSource(`/api/projects/${project.id}/logs/stream`); events.addEventListener("log", (event) => { try { const update = JSON.parse(event.data); setLogs(update.logs || "No runtime output has been received yet.\n"); setStatus(update.status || ""); } catch { /* Ignore malformed stream frames. */ } }); events.onerror = () => events.close(); return () => events.close(); }, [project.id]);
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="logs-title"><section className="glass strong modal"><div className="wizard-top"><div><p className="eyebrow">LIVE DEPLOYMENT LOGS</p><h2 id="logs-title">{project.name}</h2><span className={`status ${statusClass(status || project.status)}`}>{statusName(status || project.status)}</span></div><button className="icon-button" onClick={onClose} aria-label="Close logs"><X size={18} /></button></div><pre className="terminal" aria-live="polite" style={{ height: "min(55vh,500px)", whiteSpace: "pre-wrap", marginTop: 18 }}>{logs}</pre><p className="tiny" style={{ margin: "10px 0 0" }}>The stream follows the latest deployment. Values from encrypted variables are never emitted by the control plane.</p></section></div>;
}

function ProjectWizard({ onClose, onCreated }: { onClose: () => void; onCreated: (message: string) => Promise<void> }) {
  const [step, setStep] = useState(1); const [draft, setDraft] = useState<Draft>(blankDraft); const [variables, setVariables] = useState([{ key: "", value: "", isSecret: true }]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const update = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  function selectRuntime(value: Draft["runtimeKey"]) { setDraft((current) => ({ ...current, runtimeKey: value, ...runtimeDefaults[value] })); }
  async function save(deploy: boolean) { setBusy(true); setError(""); try { const response = await fetch("/api/projects", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...draft, memoryMb: Number(draft.memoryMb), cpuLimit: Number(draft.cpuLimit), internalPort: draft.internalPort ? Number(draft.internalPort) : undefined, restartPolicy: "unless-stopped" }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Project could not be saved."); for (const variable of variables.filter((item) => item.key && item.value)) { const result = await fetch(`/api/projects/${body.project.id}/variables`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(variable) }); if (!result.ok) throw new Error("Project was created, but a variable could not be encrypted and saved."); } if (deploy) { const result = await fetch(`/api/projects/${body.project.id}/deploy`, { method: "POST" }); const resultBody = await result.json(); if (!result.ok) throw new Error(`Project saved. ${resultBody.error || "Runner could not start deployment."}`); await onCreated("Deployment queued with the isolated runner."); } else await onCreated("Project saved as a draft. Add source files, then deploy from the project controls."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save project."); setBusy(false); } }
  function submit(event: FormEvent) { event.preventDefault(); step < 4 ? setStep(step + 1) : save(false); }
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="wizard-title"><form className="glass strong modal" onSubmit={submit}><div className="wizard-top"><div><p className="eyebrow">NEW DEPLOYMENT</p><h2 id="wizard-title">Add an authorized project</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close project wizard"><X size={18} /></button></div><div className="steps" aria-label={`Step ${step} of 4`}>{[1, 2, 3, 4].map((item) => <span className={item <= step ? "active" : ""} key={item} />)}</div>
    {step === 1 && <><p className="muted" style={{ marginTop: 0, fontSize: 13 }}>Choose a source you own or are explicitly authorized to deploy.</p><div className="source-grid">{sourceOptions.map(({ value, icon: Icon, label, text }) => <button type="button" className={`choice ${draft.sourceType === value ? "selected" : ""}`} key={value} onClick={() => update("sourceType", value as Draft["sourceType"])}><Icon size={19} color="var(--accent-cyan)" /><b>{label}</b><span>{text}</span></button>)}</div>{["GITHUB", "GIT"].includes(draft.sourceType) && <label className="field-label" style={{ marginTop: 16 }}>Repository URL <input className="field mono" value={draft.repositoryUrl} onChange={(event) => update("repositoryUrl", event.target.value)} placeholder="https://github.com/owner/repository.git" required /></label>}<p className="tiny" style={{ marginBottom: 0 }}>GitHub OAuth selection appears only after administrator credentials are configured; direct Git URLs remain supported for authorized repositories.</p></>}
    {step === 2 && <div className="fields-grid"><label className="field-label">Project name <input className="field" value={draft.name} onChange={(event) => update("name", event.target.value)} placeholder="e.g. support-api" required /></label><label className="field-label">Project type <select className="field" value={draft.type} onChange={(event) => update("type", event.target.value as Draft["type"])}>{["WEB_SERVICE", "API", "DISCORD_BOT", "TELEGRAM_BOT", "WHATSAPP_INTEGRATION", "BACKGROUND_WORKER", "STATIC_WEBSITE", "SCHEDULED_JOB"].map((value) => <option value={value} key={value}>{statusName(value)}</option>)}</select></label><label className="field-label">Runtime <select className="field" value={draft.runtimeKey} onChange={(event) => selectRuntime(event.target.value as Draft["runtimeKey"])}>{Object.keys(runtimeDefaults).map((value) => <option value={value} key={value}>{value === "node" ? "Node.js" : value === "php" ? "PHP" : statusName(value)}</option>)}</select></label><label className="field-label">Branch <input className="field mono" value={draft.branch} onChange={(event) => update("branch", event.target.value)} /></label><label className="field-label">Install command <input className="field mono" value={draft.installCommand} onChange={(event) => update("installCommand", event.target.value)} /></label><label className="field-label">Build command <input className="field mono" value={draft.buildCommand} onChange={(event) => update("buildCommand", event.target.value)} /></label><label className="field-label">Start command <input className="field mono" value={draft.startCommand} onChange={(event) => update("startCommand", event.target.value)} required /></label><label className="field-label">Internal port <input type="number" min="1" max="65535" className="field mono" value={draft.internalPort} onChange={(event) => update("internalPort", event.target.value)} placeholder="Not public by default" /></label></div>}
    {step === 3 && <><p className="muted" style={{ marginTop: 0, fontSize: 13 }}>Values are encrypted before database storage and can only be replaced later—not listed in plaintext.</p>{variables.map((variable, index) => <div className="variable-row" key={index}><input className="field mono" aria-label="Variable key" placeholder="VARIABLE_KEY" value={variable.key} onChange={(event) => setVariables((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, key: event.target.value.toUpperCase() } : item))} /><input className="field mono" aria-label="Variable value" placeholder="Value" type={variable.isSecret ? "password" : "text"} value={variable.value} onChange={(event) => setVariables((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, value: event.target.value } : item))} /><button className="soft-button" type="button" onClick={() => setVariables((items) => items.length === 1 ? items.map((item) => ({ ...item, isSecret: !item.isSecret })) : items.filter((_, itemIndex) => itemIndex !== index))}>{variables.length === 1 ? (variable.isSecret ? "Secret" : "Plain") : "Remove"}</button></div>)}<button className="soft-button" type="button" style={{ marginTop: 10 }} onClick={() => setVariables((items) => [...items, { key: "", value: "", isSecret: true }])}><Plus size={14} style={{ verticalAlign: "middle", marginRight: 6 }} />Add variable</button></>}
    {step === 4 && <><div className="fields-grid"><label className="field-label">Memory limit (MB) <input className="field mono" type="number" min="128" max="32768" value={draft.memoryMb} onChange={(event) => update("memoryMb", event.target.value)} /></label><label className="field-label">CPU limit (cores) <input className="field mono" type="number" min="0.1" max="16" step="0.1" value={draft.cpuLimit} onChange={(event) => update("cpuLimit", event.target.value)} /></label></div><div className="terminal" style={{ marginTop: 17 }}><div className="info">$ deployment review</div><div>source: {draft.sourceType} {draft.repositoryUrl ? `→ ${draft.repositoryUrl}` : ""}</div><div>runtime: {draft.runtimeKey} · command: {draft.startCommand}</div><div>limits: {draft.memoryMb} MB · {draft.cpuLimit} CPU · unless-stopped</div><div>variables: {variables.filter((item) => item.key).length} encrypted record(s)</div><div className="ok">✓ Workloads will run as non-root in an isolated container.</div></div></>}
    {error && <p className="form-message error" role="alert">{error}</p>}<div className="wizard-footer"><button type="button" className="soft-button" onClick={() => step === 1 ? onClose() : setStep(step - 1)}>{step === 1 ? "Cancel" : "Back"}</button><div style={{ display: "flex", gap: 9 }}>{step === 4 && <button type="button" className="soft-button" disabled={busy} onClick={() => save(true)}>{busy ? "Working…" : "Deploy now"}</button>}<button type="submit" className="neon-button" disabled={busy}>{step === 4 ? "Save as draft" : <>Continue <ChevronRight size={15} style={{ verticalAlign: "middle" }} /></>}</button></div></div>
  </form></div>;
}
